# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_city.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10smart_city.proto\x12\tsmartcity\"&\n\x10\x44iscoveryRequest\x12\x12\n\ngateway_id\x18\x01 \x01(\t\"\x80\x01\n\x11\x44iscoveryResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.smartcity.DeviceType\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x10\n\x08tcp_port\x18\x04 \x01(\x05\x12\x15\n\rinitial_state\x18\x05 \x01(\t\"A\n\nDataStream\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x90\x01\n\x07\x43ommand\x12)\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x19.smartcity.Command.Action\x12\x11\n\tparameter\x18\x02 \x01(\x02\"G\n\x06\x41\x63tion\x12\x0b\n\x07TURN_ON\x10\x00\x12\x0c\n\x08TURN_OFF\x10\x01\x12\x0f\n\x0b\x43HANGE_FREQ\x10\x02\x12\x11\n\rSET_THRESHOLD\x10\x03*Z\n\nDeviceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bTEMPERATURE\x10\x01\x12\x0f\n\x0b\x41IR_QUALITY\x10\x02\x12\x11\n\rTRAFFIC_LIGHT\x10\x03\x12\n\n\x06\x43\x41MERA\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_city_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICETYPE._serialized_start=416
  _DEVICETYPE._serialized_end=506
  _DISCOVERYREQUEST._serialized_start=31
  _DISCOVERYREQUEST._serialized_end=69
  _DISCOVERYRESPONSE._serialized_start=72
  _DISCOVERYRESPONSE._serialized_end=200
  _DATASTREAM._serialized_start=202
  _DATASTREAM._serialized_end=267
  _COMMAND._serialized_start=270
  _COMMAND._serialized_end=414
  _COMMAND_ACTION._serialized_start=343
  _COMMAND_ACTION._serialized_end=414
# @@protoc_insertion_point(module_scope)
